### ISSUE TITLE
David's Priority For Jan 26-Feb 1

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/cwp-com#5]
In rough order of priority, knowing this isn't all happening:
- [x] [Fix auto populate problem for search forms](https://bitbucket.org/calderadev/caldera-easy-pods/issue/8/auto-populate-search-option-from-an-easy)
- [ ] [Fix the deploy process](https://github.com/CalderaWP/cwp-com/issues/8)
- [x] Give Josh admin access to docs.calderaforms.com
- [x] CF-Stripe [New Release Check List Steps 1-4](https://github.com/CalderaWP/sops/wiki/New-Release-Check-List)
- [x] CF-MailChimp [New Release Check List Steps 1-4](https://github.com/CalderaWP/sops/wiki/New-Release-Check-List)
- [x] CF-PayPal [New Release Check List Steps 1-4](https://github.com/CalderaWP/sops/wiki/New-Release-Check-List)
- [x] CF-User-Registration [New Release Check List Steps 1-4](https://github.com/CalderaWP/sops/wiki/New-Release-Check-List)
- [x] CF-Zapier [New Release Check List Steps 1-4](https://github.com/CalderaWP/sops/wiki/New-Release-Check-List)
- [x] CF-Downloader [New Release Check List Steps 1-4](https://github.com/CalderaWP/sops/wiki/New-Release-Check-List)
- [ ] CF-Dropbox-Picker [New Release Check List Steps 1-4](https://github.com/CalderaWP/sops/wiki/New-Release-Check-List)
- [ ] CF-Nexmo [New Release Check List Steps 1-4](https://github.com/CalderaWP/sops/wiki/New-Release-Check-List)
- [ ] CF-Pushover [New Release Check List Steps 1-4](https://github.com/CalderaWP/sops/wiki/New-Release-Check-List)

**Comment by DavidCramer** [comment]
making progress
